### ISSUE TITLE
Ember Truncate is unable to convert <br> to space

### ISSUE THREAD

**Issue by shegupta** [nickiaconis/ember-truncate#16]
When to be truncated element is like following:

<p id="ember7544" class="pv-top-card-section__summary Sans-15px-black-55% mt5 ember-view">   
    I want to change the world for the better; but then again, don't we all?
   <br>
   <br>
    My approach to changing the world is through advancing public health. I am passionate about a   wide range of public health issues, particularly those involving disease surveillance and improving health systems to yield better results.
  <button class="truncate-multiline--button" data-ember-action="" data-ember-action-7989="7989">
    See less
  </button>
</p>

it's unable to convert <br> to space and return truncated content as:
 <div class="truncate-multiline--truncation-target"><span>I want to change the world for the better; but then again, don't we all?My approach to changing the world is through </span><span class="truncate-multiline--last-line-wrapper"><span class="truncate-multiline--last-line">advancing public health. I am passionate about a wide range of public health issues, particularly those involving disease surveillance and improving health systems to yield better results.</span><button class="truncate-multiline--button" data-ember-action="" data-ember-action-7990="7990">
    See more
  </button></span></div>

Please notice " don't we all?My approach to" their is no space between "?" and "My"

**Comment by nickiaconis** [comment]
Hi @shegupta! Thanks for calling attention to this; it definitely sounds like there's room for improvement. Would you be interested in implementing a solution? I can provide any advice you might need and help shepherd through a PR.

**Comment by shegupta** [comment]
Sure.

**Comment by nickiaconis** [comment]
Closed by #21.
