### ISSUE TITLE
Move away from didUpdateAttrs Arguments

### ISSUE THREAD

**Issue by nlfurniss** [nickiaconis/ember-truncate#20]
[didUpdateAttrs Arguments Deprecated](https://emberjs.com/deprecations/v2.x/#toc_code-didreceiveattrs-code-and-code-didupdateattrs-code-arguments)

This component relies on this behavior to know when to reset its state. Need to figure out a different way to do this.

**Comment by alecho** [comment]
Could you use a computed property on `text` for this?

**Comment by stickbyatlas** [comment]
Thanks for the PR to address the deprecation warnings. Wish I could assist in fixing the failing test, as I'm being bombarded by warnings myself. Hope you get some assistance soon.
